import { useState } from 'react'
import type { ReactNode } from 'react'
import { Link, Route, Routes, useLocation } from 'react-router-dom'
import { ArrowUpRight, ChevronDown, Compass, Menu, Play, Sparkles, X } from 'lucide-react'

const navItems = [
  { label: 'The experience', to: '/experience' },
  { label: 'Our stories', to: '/stories' },
  { label: 'For partners', to: '/partners' },
]

function Logo() {
  return <Link className="logo" to="/" aria-label="StoryLense home"><span className="logo-mark">✦</span><span>story<span>lense</span></span></Link>
}

function Header() {
  const [open, setOpen] = useState(false)
  const location = useLocation()
  return <header className="site-header">
    <div className="nav-shell">
      <Logo />
      <nav className={open ? 'nav-links is-open' : 'nav-links'} aria-label="Primary navigation">
        {navItems.map(item => <Link key={item.to} className={location.pathname === item.to ? 'active' : ''} to={item.to} onClick={() => setOpen(false)}>{item.label}</Link>)}
        <Link className="nav-cta" to="/partners" onClick={() => setOpen(false)}>Start a conversation <ArrowUpRight size={16} /></Link>
      </nav>
      <button className="menu-toggle" onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'}>{open ? <X /> : <Menu />}</button>
    </div>
  </header>
}

function Footer() {
  return <footer className="site-footer"><div className="footer-top"><Logo /><p>History you can play.<br />A new way to visit the past.</p><div className="footer-links"><div><span className="eyebrow">Explore</span>{navItems.map(item => <Link key={item.to} to={item.to}>{item.label}</Link>)}</div><div><span className="eyebrow">Contact</span><a href="mailto:hello@storylense.com">hello@storylense.com</a><a href="#top">Back to top ↑</a></div></div></div><div className="footer-bottom"><span>© 2026 StoryLense Technologies GmbH</span><span>Concept website · Details to follow</span><span aria-label="Social channels">✦</span></div></footer>
}

function PageShell({ children }: { children: ReactNode }) { return <><Header /><main>{children}</main><Footer /></> }

function CastleArt({ small = false }: { small?: boolean }) { return <div className={small ? 'castle-art small' : 'castle-art'} aria-label="Atmospheric castle illustration"><div className="moon" /><div className="star star-one">✦</div><div className="star star-two">✦</div><div className="castle-silhouette"><i /><i /><i /><b /><b /><b /></div><div className="hill" /></div> }

function VideoPlaceholder() { return <section className="video-section section-wrap"><div className="video-copy"><span className="eyebrow">A glimpse inside</span><h2>Step into the story.</h2><p>Picture a quiet courtyard. Then put on the lens and watch a moment from 1331 unfold around your family.</p><span className="video-note"><span className="pulse-dot" /> Film coming soon</span></div><div className="video-placeholder" role="img" aria-label="Preview image placeholder for the future StoryLense video"><CastleArt small /><div className="video-overlay"><span className="play-ring"><Play fill="currentColor" size={17} /></span><span>Video preview</span></div></div></section> }

function Home() { return <PageShell><section className="hero" id="top"><div className="hero-content"><span className="eyebrow">StoryLense · AR story games</span><h1>History<br /><em>you can play.</em></h1><p className="hero-lede">Turn a day at the castle into a family adventure. Step into another time, take a role, and make the story yours.</p><Link className="button button-light" to="/experience">Discover the experience <ArrowUpRight size={17} /></Link></div><CastleArt /><div className="scroll-cue"><span>Scroll to explore</span><span className="line" /></div></section><VideoPlaceholder /><section className="family-section section-wrap"><div className="section-heading"><span className="eyebrow">One story, every role</span><h2>A castle visit<br /><em>with a little more magic.</em></h2></div><div className="family-grid"><div className="family-card kids"><span className="card-number">01</span><Sparkles /><h3>For curious kids</h3><p>A magic lens. A mission to complete. History becomes something to touch, chase and remember.</p><Link to="/experience">See how it works <ArrowUpRight size={15} /></Link></div><div className="family-card grownups"><span className="card-number">02</span><Compass /><h3>For the whole family</h3><p>Everyone gets their own part in the story — while the real castle stays at the centre of the experience.</p><Link to="/experience">Explore the experience <ArrowUpRight size={15} /></Link></div></div></section><section className="story-preview"><div className="story-preview-art"><CastleArt small /><span className="story-tag">Concept chapter 01</span></div><div className="story-preview-copy"><span className="eyebrow">Our first story</span><h2>The Siege<br /><em>of Eltz, 1331.</em></h2><p>Six stations. One castle under threat. A family becomes its youngest line of defence.</p><Link className="text-link" to="/stories">Follow the chapter <ArrowUpRight size={16} /></Link></div></section><section className="partner-banner"><div><span className="eyebrow">For castles & cultural partners</span><h2>Bring your walls<br /><em>back to life.</em></h2></div><Link className="button button-gold" to="/partners">Partner with StoryLense <ArrowUpRight size={17} /></Link></section></PageShell> }

function InteriorHero({ eyebrow, title, intro }: { eyebrow: string; title: ReactNode; intro: string }) { return <section className="interior-hero"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{intro}</p></div><CastleArt small /></section> }

function Experience() { const faqs = ['Who is StoryLense for?', 'How do families play together?', 'What happens at the castle?']; return <PageShell><InteriorHero eyebrow="The experience" title={<>A story<br /><em>in your hands.</em></>} intro="StoryLense turns the castle visit into a shared adventure — with a role for every curious mind." /><section className="steps section-wrap"><span className="eyebrow">How it unfolds</span><div className="steps-list">{[['01','Arrive at the castle','Pick up your lens, choose your role and get ready to look at the familiar in a new way.'],['02','Enter the story','Follow clues through real rooms and courtyards as the past begins to appear around you.'],['03','Play your part','Solve a challenge together. Every person sees the story from a different angle.'],['04','Leave with a memory','The castle stays with you long after the final scene.']].map(step => <article className="step" key={step[0]}><span>{step[0]}</span><div><h3>{step[1]}</h3><p>{step[2]}</p></div></article>)}</div></section><section className="roles-section"><div className="section-wrap"><span className="eyebrow">Choose your lens</span><div className="roles-grid"><article><div className="role-icon">✦</div><h2>The magic lens</h2><p>Designed for younger adventurers. It gives children a mission, a point of view and a reason to look closer.</p><small>For kids aged 6–12 · Concept in development</small></article><article><div className="role-icon glasses">◌</div><h2>AR glasses</h2><p>A deeper layer for older players, with historical detail that brings the world around them into focus.</p><small>For ages 13+ · Concept in development</small></article></div></div></section><section className="faq section-wrap"><span className="eyebrow">Good to know</span><h2>Questions families<br /><em>might ask.</em></h2>{faqs.map(q => <details key={q}><summary>{q}<ChevronDown size={18} /></summary><p>StoryLense is a concept for family-friendly, shared AR story games at historic sites. More practical details will follow as the first chapters take shape.</p></details>)}</section></PageShell> }

const stations = [['01','The castle gate','Surrender or fight? The first decision sets the story in motion.'],['02','The inner courtyard','Three families unite as the siege closes in.'],['03','The guided tour','Find the Rose of Silence before it is too late.'],['04','The treasury','Arm the defenders with what the castle can offer.'],['05','The outer wall','The enemy builds above you. Look up.'],['06','Back at the gate','Peace — and a castle given as a gift.']]
function Stories() { return <PageShell><InteriorHero eyebrow="Our stories · Concept chapter 01" title={<>The Siege<br /><em>of Eltz, 1331.</em></>} intro="A first glimpse at the kind of chapter StoryLense could bring to a real castle. Burg Eltz is our concept example." /><section className="story-intro section-wrap"><div className="quote-mark">“</div><p className="large-quote">A family arrives on a quiet Sunday. By the time they leave, the castle has asked them to defend it.</p><p>This chapter is a creative concept, developed to show the StoryLense format. It does not represent a current partnership or available visit.</p></section><section className="stations section-wrap"><span className="eyebrow">Six moments in one chapter</span><div className="stations-list">{stations.map(s => <article className="station" key={s[0]}><span>{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div></article>)}</div></section><section className="next-chapter"><span className="eyebrow">More stories to come</span><h2>Every castle<br /><em>has a chapter.</em></h2></section></PageShell> }

function Partners() { return <PageShell><InteriorHero eyebrow="For castles & cultural partners" title={<>Give history<br /><em>a new audience.</em></>} intro="StoryLense helps historic places welcome families with stories that are made for the rooms, walls and people who care for them." /><section className="partner-copy section-wrap"><div><span className="eyebrow">A shared project</span><h2>Built around<br /><em>the real place.</em></h2></div><div><p>Every chapter begins with the castle itself. Our story and game team works alongside site staff and historians to turn local history into an experience families can share.</p><p>The castle remains the hero. StoryLense adds a reason to look closer, stay longer and come back with someone you love.</p></div></section><section className="model-section"><div className="section-wrap"><span className="eyebrow">A concept model</span><div className="model-grid"><article><span>01</span><h3>Families play</h3><p>A small add-on at the ticket desk lets each family enter the chapter with a device.</p></article><article><span>02</span><h3>Funders build</h3><p>Foundations, heritage charities and local sponsors can help bring each new chapter to life.</p></article><article><span>03</span><h3>Castles share</h3><p>Participating sites could earn a share from every game played. The exact model will be developed with partners.</p></article></div></div></section><section className="contact-section section-wrap"><span className="eyebrow">Start a conversation</span><h2>Have a place<br /><em>with a story?</em></h2><p>We are shaping the first chapters now and would love to hear from castle teams, cultural organisations and funders.</p><a className="button button-gold" href="mailto:hello@storylense.com">hello@storylense.com <ArrowUpRight size={17} /></a></section></PageShell> }

export default function App() { return <Routes><Route path="/" element={<Home />} /><Route path="/experience" element={<Experience />} /><Route path="/stories" element={<Stories />} /><Route path="/partners" element={<Partners />} /><Route path="*" element={<Home />} /></Routes> }
